const apiURL=process.env.REACT_APP_API_URL;
const AuthApiURL=process.env.REACT_APP_AUTH_API_URL;
export const urlGeneros=`${apiURL}/generos`
export const urlActores=`${apiURL}/actores`;
export const urlCines=`${apiURL}/cines`;
export const urlPeliculas=`${apiURL}/peliculas`;
export const urlCuentas=`${apiURL}/usuarios`; 
export const urlCategorias=`${apiURL}/categorias`; 
export const urlAuth=`${AuthApiURL}`; 
export const urlProductos=`${apiURL}/productos`; 
export const urlSolicitudes=`${apiURL}/solicitudes`; 
export const urlCarrito=`${apiURL}/carrito`; 
export const urlClaveValor=`${apiURL}/clavevalor`; 
export const urlAcciones=`${apiURL}/acciones`; 
export const urlRoles=`${apiURL}/Roles`;
